### ISSUE TITLE
Next Steps for Mapping Data

### ISSUE THREAD

**Issue by linnva** [JinmanX/Data-Fair-G18#1]
Here is my suggestion for our next steps:

Based on the conflictlocation file from 23nd October (to start with):

Additional cleaning steps: 

- use separator package to divide hashtags or words (e.g. #ArmeniaStopWar)
- Filter for 'news', 'media' , 'global', 'UK', 'US', 'politics', 'info', 'information' OR users more than 2500 followers
- Drop all rows with irrelevant hashtags - not case sensitive (top 10 hashtags such as work / management / fitness / Manage / Leadership / coaching / workplace /conflictmanagement / employees / unproductive / companyif applicable)
- Drop all rows with only one hashtag (conflict) --> wont give as any additional value/information

1. Create DataFrame with lat and on (latitude and longitude) values. Drop all rows without location. This can be achieved with Geocoding. For example, we can use GeoPy (check this out: https://towardsdatascience.com/geocode-with-python-161ec1e62b89 or https://geopy.readthedocs.io/en/latest/#nominatim)

2. Add sentiment value, hashtags, username and time for each row

3. Identify top tokenised words AND top hashtags used. Based on that decide which major event to concentrate on (lets say Armenia, Azerbaijan, Covid). Maybe: Segregate these in different DataFrames 

4. After geocoding and cleaning, perform mapping with plotly:
https://medium.com/analytics-vidhya/plotly-for-geomaps-bb75d1de189f

5. If we want to be really funky (and have time) then we can also do a real-time stream of #conflict tweets VS #peace tweets:
https://medium.com/dev-genius/twitter-api-data-visualizations-with-pandas-and-plotly-1e9d0c00ab26

DOCUMENTATION FOR GEOPY: https://geopy.readthedocs.io/en/stable/#nominatim

**Comment by JinmanX** [comment]
Thank you for the work, V! I really like idea of bubble map

Here is my research about other packages:
- There are two libraries base on `leaflet.js`(maybe `ipyleaflet` in jupyter) , `folium` and `mapboxgl` (based on mapbox token, some `plotly` packages need it too) 
- `Bokeh` uses `mercator` to locate or GeoJson Data. Also working with `Geopandas` is great.
> [Bokeh Docs](https://docs.bokeh.org/en/latest/docs/user_guide/geo.html), [Some tutorials](https://automating-gis-processes.github.io/2017/lessons/L5/interactive-map-bokeh.html)
- Slider tool below could realize our idea of timeline.
> [Slider Bar](https://towardsdatascience.com/walkthrough-mapping-basics-with-bokeh-and-geopandas-in-python-43f40aa5b7e9)
- Also a dropdown widget can be useful.
> [look at A more advanced example](https://blog.jupyter.org/interactive-gis-in-jupyter-with-ipyleaflet-52f9657fa7a)

PS:
- I'm working on a tool to scrape more data which seems taking time and some data type is different. Don't worry I will try to make it same, we can work on the old data now if necessary. 
- If we really need to use those python libraries, create a location column with `GeoCode` is important. The original location is multifarious!
- I highly recommend Tonye can draw some demos to show our future possible work on our website, because I think our idea of node links is really interesting.

**Comment by linnva** [comment]
Great thanks! I have prepared a code that cleans the hashtags using WordSeperator and got rid of columns without locations. By tomorrow, we should have a dataframe with clean tweet, clean hashtag, hashtag count, lat and long geocoding values.

I am looking into leaflet.js as well (plotly is based on leaflet) and will look into folium. I tried Geopanda to get the lat and long data, it works for me.

**Comment by linnva** [comment]
Good work, guys! Both folium and plotly seem to be a good and easy method suitable for our Python environment.
